name: RozsLib
version: '1.6'
main: net.weesli.rozsLib.RozsLib
api-version: '1.13'
author: Weesli
depend: [PlaceholderAPI]
commands:
  # Commands for RozsLib
  RLib:
    description: 'RozsLib commands'
